node_type: eagerx_core.rxnode/ActionsNode
default:
  inputs: [observations_set, step]
  outputs: []
  single_process: true
  launch_locally: true
  color: yellow
inputs:
  observations_set:
    address: env/observations/outputs/set
    msg_type: std_msgs.msg/UInt64
    repeat: all
  step:
    address: env/supervisor/outputs/step
    msg_type: std_msgs.msg/UInt64
    repeat: all
outputs: {}