node_type: eagerx_core.rxsupervisor/SupervisorNode
default:
  outputs: [step]
  states: []
  single_process: true
  launch_locally: true
  color: yellow
outputs:
  step:
    msg_type: std_msgs.msg/UInt64
states: {}