default:
  sensors: [N6, N7]
  actuators: [ref_vel]
  states: [N9, N10]
  position: [0, 0, 0]
  orientation: [0, 0, 0]

#########################
## Agnostic definition ##
#########################
sensors: # inputs of env
  N6:
    rate: 1
    msg_type: std_msgs.msg/UInt64
  N7:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]

actuators: # outputs of env
  N8:
    rate: 2
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: 0
      high: 100
      shape: (1,)  # optional
  ref_vel:
    rate: 1
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]

states:  # reset states inside bridge
  N9:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]
  N10:
    msg_type: std_msgs.msg/UInt64
    space_converter:
      converter_type: eagerx_core.converter/SpaceUInt64Converter
      dtype: uint64
      low: [0]
      high: [100]

#########################
### Engine definition ###
#########################
bridge:
  urdf: 'path/to/urdf.urdf'
  sensors:
    N6:
      node_config: eagerx_core/sim_sensor # These nodes cannot have an internal state
      states: [error]
      color: cyan
#      single_process: False
#      launch_locally: False
      test_arg: 'CHANGED ARGUMENT'
    N7:
      node_config: eagerx_core/sim_sensor # These nodes cannot have an internal state
      inputs: {in_1: sensors/N6}
      color: cyan
#      single_process: False
#      launch_locally: False
      test_arg: 'CHANGED ARGUMENT'

  actuators:  # Inputs as defined above
    N8:
      node_config: eagerx_core/sim_actuator
      inputs: {action_1: , # actuator input mapping to sim_node input name inside node_config "sim_actuator.yaml"
               action_2: sensors/N6}  # inputs to nodes must always originate from within the node itself.
      color: green
#      single_process: False
#      launch_locally: False
#      input_convert:  # can only contain converters for inputs other than "actuator_input"
#        action_2:
#          converter_type: eagerx_core.converter/SpaceUInt64Converter
#          test_arg: 'test'
      test_arg: 'CHANGED ARGUMENT'

  states:
    N9:
      state_type: eagerx_core.rxsimstate/TestSimState
      test_arg: 'CHANGED ARGUMENT'

    N10:
      state_type: eagerx_core.rxsimstate/TestSimState
      test_arg: 'CHANGED ARGUMENT'

